### ISSUE TITLE
Indy version compatability?

### ISSUE THREAD

**Issue by aim12340** [IndySockets/IndyTLS-OpenSSL#21]
What is the earilest verison of Indy this should work with?

I'm having probems installing this with Indy 10.6.2.0 on Delphi XE.  

I don't want to bore anyone with the problem if what I really need is to update Indy.

Thanks.

**Comment by rlebeau** [comment]
This IndyTLS-OpenSSL project is fairly new and has NOT been finalized for its initial release yet.

Basically, OpenSSL support is in the process of being refactored out of the main Indy library and moved into this project.  As such, there is no point in trying to use this project with earlier versions of Indy, as they have the same OpenSSL code built-in to them.

After this project's initial release, it will be updated to support modern OpenSSL, and will likely be compatible only with the current version of Indy at that time, going forward.  If a user wants to use this project, they should use it with an up-to-date Indy version.  If they really want to keep using an older Indy version, they will have to make the appropriate alterations to Indy and recompile it to remove the built-in OpenSSL code.  In which case, they may as well just upgrade to the latest Indy anyway.

**Comment by aim12340** [comment]
Thanks Remy.  Not what I expected, so I'll just keep watching for a release.

For now I can jimmy something together with curl to get my work done.
