### ISSUE TITLE
Missing uses declaration and file

### ISSUE THREAD

**Issue by SiveaITA** [IndySockets/IndyTLS-OpenSSL#3]
In order for everything to compile correctly, there are two changes to make:

1) In the "IdRegisterOpenSSL.pas" file it is necessary to insert the following file "IdDsnCoreResourceStrings" among the uses because it is inside it that the string "RSRegIndyIOHandlers" is defined, which is necessary to register the design time components.

2) The "IdRegisterCoolOpenSSL.dcr" file is missing .... just copy it (and then rename obviously) from the "IdRegisterCool.dcr" file from original distro. 

(EDIT: the second it is already resolved, ... I didn't notice that.)

**Comment by rlebeau** [comment]
`IdDsnCoreResourceStrings` has been added to `IdRegisterOpenSSL.pas`.

`IdRegisterCoolOpenSSL.dcr` has been removed in favor of using just `IdRegisterOpenSSL.dcr` by itself.

commit [8a1aee0](https://github.com/IndySockets/IndyTLS-OpenSSL/commit/8a1aee08756927e240fa8229d3d2f7028ce922f8)
